#!/usr/bin/env bash
set -Eeuo pipefail

REPO="${KOMARI_SAFE_REPO:-suckdrygod/tcpping}"
INSTALL_DIR='/opt/komari'
BINARY="$INSTALL_DIR/agent"
SERVICE='/etc/systemd/system/komari-agent.service'

endpoint=''
token=''
month_rotate='0'
timezone=''
allow_hosts='*.ip.zstaticcdn.com'
allow_ports='80,443'
timeout='3'
rate='30'

usage() {
  cat <<USAGE
Usage:
  $0 -e ENDPOINT -t TOKEN [options]

Required:
  -e, --endpoint URL                 Komari endpoint, for example https://agent.example.com
  -t, --token TOKEN                  Node token generated by your Komari panel

TCP-safe policy options:
      --safe-tcp-allow-hosts LIST    Exact hosts or *.suffix patterns (default: *.ip.zstaticcdn.com)
      --safe-tcp-allow-ports LIST    Destination TCP ports (default: 80,443)
      --safe-tcp-timeout SECONDS     Per-probe timeout, 1-10 (default: 3)
      --safe-tcp-rate PER_MINUTE     Accepted tasks per minute, 1-120 (default: 30)

Other:
      --month-rotate DAY             Network-statistics monthly reset day, 0-31 (default: 0)
      --timezone IANA_NAME           Timezone used for reset boundaries (default: VPS timezone)
      --repo OWNER/REPO              Release repository override
  -h, --help                         Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -e|--endpoint) endpoint="${2:?missing endpoint}"; shift 2 ;;
    -t|--token) token="${2:?missing token}"; shift 2 ;;
    --month-rotate) month_rotate="${2:?missing day}"; shift 2 ;;
    --timezone) timezone="${2:?missing timezone}"; shift 2 ;;
    --safe-tcp-allow-hosts) allow_hosts="${2:?missing host list}"; shift 2 ;;
    --safe-tcp-allow-ports) allow_ports="${2:?missing port list}"; shift 2 ;;
    --safe-tcp-timeout) timeout="${2:?missing timeout}"; shift 2 ;;
    --safe-tcp-rate) rate="${2:?missing rate}"; shift 2 ;;
    --repo) REPO="${2:?missing repository}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo 'Run as root or with sudo.' >&2; exit 1; }
[[ -n "$endpoint" && -n "$token" ]] || { usage >&2; exit 2; }
[[ "$timeout" =~ ^[0-9]+$ ]] && (( timeout >= 1 && timeout <= 10 )) || { echo 'Invalid --safe-tcp-timeout.' >&2; exit 2; }
[[ "$rate" =~ ^[0-9]+$ ]] && (( rate >= 1 && rate <= 120 )) || { echo 'Invalid --safe-tcp-rate.' >&2; exit 2; }
[[ "$month_rotate" =~ ^[0-9]+$ ]] && (( month_rotate >= 0 && month_rotate <= 31 )) || { echo 'Invalid --month-rotate.' >&2; exit 2; }

if [[ -z "$timezone" ]]; then
  if command -v timedatectl >/dev/null 2>&1; then
    timezone="$(timedatectl show --property=Timezone --value 2>/dev/null || true)"
  fi
  if [[ -z "$timezone" && -r /etc/timezone ]]; then
    timezone="$(tr -d '[:space:]' </etc/timezone)"
  fi
  if [[ -z "$timezone" && -L /etc/localtime ]]; then
    timezone="$(readlink -f /etc/localtime | sed 's#^/usr/share/zoneinfo/##')"
  fi
  timezone="${timezone:-Etc/UTC}"
fi
[[ "$timezone" =~ ^[A-Za-z0-9_+./-]+$ ]] || { echo 'Invalid --timezone.' >&2; exit 2; }
[[ -e "/usr/share/zoneinfo/$timezone" ]] || { echo "Timezone not found: $timezone" >&2; exit 2; }

case "$(uname -m)" in
  x86_64|amd64) arch='amd64' ;;
  aarch64|arm64) arch='arm64' ;;
  *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

command -v curl >/dev/null 2>&1 || { echo 'curl is required.' >&2; exit 1; }
command -v sha256sum >/dev/null 2>&1 || { echo 'sha256sum is required.' >&2; exit 1; }
mkdir -p "$INSTALL_DIR"
tmp="$(mktemp)"
sumtmp="$(mktemp)"
trap 'rm -f "$tmp" "$sumtmp"' EXIT
asset="komari-agent-linux-${arch}"
url="https://github.com/${REPO}/releases/latest/download/${asset}"
checksums_url="https://github.com/${REPO}/releases/latest/download/SHA256SUMS"
echo "Downloading TCP-safe agent for ${arch}..."
curl -fL --proto '=https' --tlsv1.2 \
  --retry 8 --retry-all-errors --retry-delay 5 --connect-timeout 20 \
  "$url" -o "$tmp"
curl -fsSL --proto '=https' --tlsv1.2 \
  --retry 8 --retry-all-errors --retry-delay 5 --connect-timeout 20 \
  "$checksums_url" -o "$sumtmp"
(cd "$(dirname "$tmp")" && grep -E "  ${asset}$" "$sumtmp" | sed "s#  ${asset}\$#  $(basename "$tmp")#" | sha256sum -c -)
chmod 0755 "$tmp"

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
if [[ -f "$BINARY" ]]; then
  cp -a "$BINARY" "${BINARY}.backup-${stamp}"
fi
if [[ -f "$SERVICE" ]]; then
  cp -a "$SERVICE" "${SERVICE}.backup-${stamp}"
fi
install -m 0755 "$tmp" "$BINARY"

cat > "$SERVICE" <<SERVICE
[Unit]
Description=Komari TCPing Safe Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=TZ=${timezone}
Environment=AGENT_SSH_LOGIN_NOTIFY=true
ExecStart=${BINARY} -e ${endpoint@Q} -t ${token@Q} --disable-auto-update --month-rotate ${month_rotate} --safe-tcp-allow-hosts ${allow_hosts@Q} --safe-tcp-allow-ports ${allow_ports@Q} --safe-tcp-timeout ${timeout} --safe-tcp-max-tasks-per-minute ${rate}
WorkingDirectory=${INSTALL_DIR}
Restart=always
RestartSec=5
User=root
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now komari-agent
systemctl restart komari-agent
systemctl --no-pager --full status komari-agent

echo
echo 'Installed Komari TCPing Safe Agent.'
echo 'Only TCP tasks matching the configured host/port allow-list are accepted.'
