#!/usr/bin/env bash
set -Eeuo pipefail

REPO="${KOMARI_SAFE_REPO:-suckdrygod/tcpping}"
INSTALL_DIR="${KOMARI_INSTALL_DIR:-/opt/komari}"
service_name="${KOMARI_SERVICE_NAME:-komari-agent}"

endpoint=''
token=''
auto_discovery=''
month_rotate='0'
timezone=''
install_ghproxy=''

safe_tcp_allow_hosts=''
safe_tcp_allow_ports=''
safe_tcp_timeout=''
safe_tcp_rate=''

ssh_auth_guard='false'
ssh_auth_aggregate_by_ip='true'
ssh_auth_threshold='5'
ssh_auth_window='60'
ssh_auth_cooldown='1800'
ssh_auth_root_only='false'
ssh_auth_ban_enable='false'
ssh_auth_ban_after='5'
ssh_auth_ban_duration='3600'
ssh_auth_ban_whitelist=''
ssh_auth_ban_mode='nftables'
ssh_auth_ban_dry_run='false'

agent_args_extra=()

usage() {
  cat <<USAGE
Usage:
  $0 -e ENDPOINT (-t TOKEN | --auto-discovery KEY) [options]

Required:
  -e, --endpoint URL                 Komari endpoint, for example https://agent.example.com
  -t, --token TOKEN                  Node token generated by your Komari panel
      --auto-discovery KEY           Auto-discovery key generated by your Komari panel

Panel-compatible install options:
      --disable-web-ssh              Accepted for compatibility; web-ssh/RCE is removed in this build
      --disable-auto-update          Accepted for compatibility; auto-update is disabled in this build
      --ignore-unsafe-cert           Ignore unsafe TLS certificates when connecting to Komari
      --memory-include-cache         Include cache/buffer in memory statistics
      --get-ip-addr-from-nic         Get IP address from NIC
      --gpu                          Enable detailed GPU monitoring
  -i, --interval SECONDS             Report interval
      --include-nics LIST            Only monitor specific NICs
      --exclude-nics LIST            Exclude specific NICs
      --include-mountpoint LIST      Only monitor specific mount points
      --install-ghproxy URL          GitHub download proxy
      --install-dir DIR              Install directory (default: /opt/komari)
      --install-service-name NAME    systemd service name (default: komari-agent)

Traffic reset:
      --month-rotate DAY             Network-statistics monthly reset day, 0-31 (default: 0)
      --timezone IANA_NAME           Timezone used for reset boundaries (default: VPS timezone)

TCP-safe policy overrides:
      --safe-tcp-allow-hosts LIST    Exact hosts or *.suffix patterns
      --safe-tcp-allow-ports LIST    Destination TCP ports
      --safe-tcp-timeout SECONDS     Per-probe timeout, 1-10
      --safe-tcp-rate PER_MINUTE     Accepted tasks per minute, 1-120

SSH Auth Guard:
      --ssh-auth-guard               Enable SSH failed-login brute-force alerts
      --ssh-auth-aggregate-by-ip     Merge users by source IP (default when guard is enabled)
      --ssh-auth-no-aggregate-by-ip  Keep legacy source IP + user aggregation
      --ssh-auth-threshold N         Failures required within window (default: 5)
      --ssh-auth-window SECONDS      Detection window (default: 60)
      --ssh-auth-cooldown SECONDS    Alert cooldown (default: 1800)
      --ssh-auth-root-only           Only alert on root failures
      --ssh-auth-ban-enable          Enable local nftables ban (default: off)
      --ssh-auth-ban-after N         Failures before local ban (default: 5)
      --ssh-auth-ban-duration SEC    Ban duration (default: 3600)
      --ssh-auth-ban-whitelist LIST  Ban whitelist, single IP or CIDR
      --ssh-auth-ban-dry-run         Log intended bans without applying nftables

Other:
      --repo OWNER/REPO              Release repository override
  -h, --help                         Show this help
USAGE
}

need_value() {
  local name="$1"
  local value="${2:-}"
  [[ -n "$value" ]] || { echo "Missing value for ${name}." >&2; exit 2; }
  printf '%s' "$value"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -e|--endpoint) endpoint="$(need_value "$1" "${2:-}")"; shift 2 ;;
    -t|--token) token="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --auto-discovery) auto_discovery="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --month-rotate) month_rotate="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --timezone) timezone="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --install-ghproxy) install_ghproxy="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --install-dir) INSTALL_DIR="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --install-service-name) service_name="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --repo) REPO="$(need_value "$1" "${2:-}")"; shift 2 ;;

    --disable-web-ssh)
      agent_args_extra+=("--disable-web-ssh")
      shift
      ;;
    --disable-auto-update)
      shift
      ;;
    --ignore-unsafe-cert|--memory-include-cache|--get-ip-addr-from-nic|--gpu)
      agent_args_extra+=("$1")
      shift
      ;;
    -i|--interval)
      agent_args_extra+=("-i" "$(need_value "$1" "${2:-}")")
      shift 2
      ;;
    --include-nics|--exclude-nics|--include-mountpoint)
      agent_args_extra+=("$1" "$(need_value "$1" "${2:-}")")
      shift 2
      ;;

    --safe-tcp-allow-hosts) safe_tcp_allow_hosts="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --safe-tcp-allow-ports) safe_tcp_allow_ports="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --safe-tcp-timeout) safe_tcp_timeout="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --safe-tcp-rate) safe_tcp_rate="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-guard) ssh_auth_guard='true'; shift ;;
    --ssh-auth-aggregate-by-ip) ssh_auth_aggregate_by_ip='true'; shift ;;
    --ssh-auth-no-aggregate-by-ip) ssh_auth_aggregate_by_ip='false'; shift ;;
    --ssh-auth-threshold) ssh_auth_threshold="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-window) ssh_auth_window="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-cooldown) ssh_auth_cooldown="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-root-only) ssh_auth_root_only='true'; shift ;;
    --ssh-auth-ban-enable) ssh_auth_ban_enable='true'; shift ;;
    --ssh-auth-ban-after) ssh_auth_ban_after="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-ban-duration) ssh_auth_ban_duration="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-ban-whitelist) ssh_auth_ban_whitelist="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-ban-mode) ssh_auth_ban_mode="$(need_value "$1" "${2:-}")"; shift 2 ;;
    --ssh-auth-ban-dry-run) ssh_auth_ban_dry_run='true'; shift ;;

    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo 'Run as root or with sudo.' >&2; exit 1; }
[[ -n "$endpoint" ]] || { usage >&2; exit 2; }
[[ -n "$token" || -n "$auto_discovery" ]] || { usage >&2; exit 2; }
[[ "$month_rotate" =~ ^[0-9]+$ ]] && (( month_rotate >= 0 && month_rotate <= 31 )) || { echo 'Invalid --month-rotate.' >&2; exit 2; }
if [[ -n "$safe_tcp_timeout" ]]; then
  [[ "$safe_tcp_timeout" =~ ^[0-9]+$ ]] && (( safe_tcp_timeout >= 1 && safe_tcp_timeout <= 10 )) || { echo 'Invalid --safe-tcp-timeout.' >&2; exit 2; }
fi
if [[ -n "$safe_tcp_rate" ]]; then
  [[ "$safe_tcp_rate" =~ ^[0-9]+$ ]] && (( safe_tcp_rate >= 1 && safe_tcp_rate <= 120 )) || { echo 'Invalid --safe-tcp-rate.' >&2; exit 2; }
fi
[[ "$ssh_auth_threshold" =~ ^[0-9]+$ ]] && (( ssh_auth_threshold >= 1 && ssh_auth_threshold <= 1000 )) || { echo 'Invalid --ssh-auth-threshold.' >&2; exit 2; }
[[ "$ssh_auth_window" =~ ^[0-9]+$ ]] && (( ssh_auth_window >= 1 && ssh_auth_window <= 3600 )) || { echo 'Invalid --ssh-auth-window.' >&2; exit 2; }
[[ "$ssh_auth_cooldown" =~ ^[0-9]+$ ]] && (( ssh_auth_cooldown >= 1 && ssh_auth_cooldown <= 86400 )) || { echo 'Invalid --ssh-auth-cooldown.' >&2; exit 2; }
[[ "$ssh_auth_ban_after" =~ ^[0-9]+$ ]] && (( ssh_auth_ban_after >= 1 && ssh_auth_ban_after <= 10000 )) || { echo 'Invalid --ssh-auth-ban-after.' >&2; exit 2; }
[[ "$ssh_auth_ban_duration" =~ ^[0-9]+$ ]] && (( ssh_auth_ban_duration >= 60 && ssh_auth_ban_duration <= 86400 )) || { echo 'Invalid --ssh-auth-ban-duration.' >&2; exit 2; }
[[ "$ssh_auth_ban_mode" == 'nftables' ]] || { echo 'Invalid --ssh-auth-ban-mode: only nftables is supported.' >&2; exit 2; }

if [[ -z "$timezone" ]]; then
  if command -v timedatectl >/dev/null 2>&1; then
    timezone="$(timedatectl show --property=Timezone --value 2>/dev/null || true)"
  fi
  if [[ -z "$timezone" && -r /etc/timezone ]]; then
    timezone="$(tr -d '[:space:]' </etc/timezone)"
  fi
  if [[ -z "$timezone" && -L /etc/localtime ]]; then
    timezone="$(readlink -f /etc/localtime | sed 's#^/usr/share/zoneinfo/##')"
  fi
  timezone="${timezone:-Etc/UTC}"
fi
[[ "$timezone" =~ ^[A-Za-z0-9_+./-]+$ ]] || { echo 'Invalid --timezone.' >&2; exit 2; }
[[ -e "/usr/share/zoneinfo/$timezone" ]] || { echo "Timezone not found: $timezone" >&2; exit 2; }
[[ "$INSTALL_DIR" = /* && "$INSTALL_DIR" != *$'\n'* ]] || { echo 'Invalid --install-dir.' >&2; exit 2; }
service_name="${service_name%.service}"
[[ "$service_name" =~ ^[A-Za-z0-9_.@-]+$ ]] || { echo 'Invalid --install-service-name.' >&2; exit 2; }

case "$(uname -m)" in
  x86_64|amd64) arch='amd64' ;;
  aarch64|arm64) arch='arm64' ;;
  *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

command -v curl >/dev/null 2>&1 || { echo 'curl is required.' >&2; exit 1; }
command -v sha256sum >/dev/null 2>&1 || { echo 'sha256sum is required.' >&2; exit 1; }

proxy_url() {
  local url="$1"
  local proxy="${install_ghproxy:-}"
  [[ -n "$proxy" ]] || { printf '%s\n' "$url"; return; }
  [[ "$proxy" == http* ]] || proxy="http://${proxy}"
  proxy="${proxy%/}"
  printf '%s/%s\n' "$proxy" "${url#https://}"
}

BINARY="$INSTALL_DIR/agent"
unit="${service_name}.service"
SERVICE="/etc/systemd/system/${unit}"

mkdir -p "$INSTALL_DIR"
tmp="$(mktemp)"
sumtmp="$(mktemp)"
trap 'rm -f "$tmp" "$sumtmp"' EXIT
asset="komari-agent-linux-${arch}"
url="$(proxy_url "https://github.com/${REPO}/releases/latest/download/${asset}")"
checksums_url="$(proxy_url "https://github.com/${REPO}/releases/latest/download/SHA256SUMS")"

echo "Downloading Komari safe agent for ${arch}..."
curl -fL --proto '=https,http' --tlsv1.2 \
  --retry 8 --retry-all-errors --retry-delay 5 --connect-timeout 20 \
  "$url" -o "$tmp"
curl -fsSL --proto '=https,http' --tlsv1.2 \
  --retry 8 --retry-all-errors --retry-delay 5 --connect-timeout 20 \
  "$checksums_url" -o "$sumtmp"
(cd "$(dirname "$tmp")" && grep -E "  ${asset}$" "$sumtmp" | sed "s#  ${asset}\$#  $(basename "$tmp")#" | sha256sum -c -)
chmod 0755 "$tmp"

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
if [[ -f "$BINARY" ]]; then
  cp -a "$BINARY" "${BINARY}.backup-${stamp}"
fi
if [[ -f "$SERVICE" ]]; then
  cp -a "$SERVICE" "${SERVICE}.backup-${stamp}"
fi
install -m 0755 "$tmp" "$BINARY"

agent_args=(-e "$endpoint")
if [[ -n "$token" ]]; then
  agent_args+=(-t "$token")
fi
if [[ -n "$auto_discovery" ]]; then
  agent_args+=(--auto-discovery "$auto_discovery")
fi
agent_args+=(--disable-auto-update --month-rotate "$month_rotate")
if [[ -n "$safe_tcp_allow_hosts" ]]; then
  agent_args+=(--safe-tcp-allow-hosts "$safe_tcp_allow_hosts")
fi
if [[ -n "$safe_tcp_allow_ports" ]]; then
  agent_args+=(--safe-tcp-allow-ports "$safe_tcp_allow_ports")
fi
if [[ -n "$safe_tcp_timeout" ]]; then
  agent_args+=(--safe-tcp-timeout "$safe_tcp_timeout")
fi
if [[ -n "$safe_tcp_rate" ]]; then
  agent_args+=(--safe-tcp-max-tasks-per-minute "$safe_tcp_rate")
fi
if [[ "$ssh_auth_guard" == 'true' ]]; then
  agent_args+=(--ssh-auth-guard --ssh-auth-threshold "$ssh_auth_threshold" --ssh-auth-window "$ssh_auth_window" --ssh-auth-cooldown "$ssh_auth_cooldown")
  if [[ "$ssh_auth_aggregate_by_ip" == 'true' ]]; then
    agent_args+=(--ssh-auth-aggregate-by-ip)
  fi
  if [[ "$ssh_auth_root_only" == 'true' ]]; then
    agent_args+=(--ssh-auth-root-only)
  fi
  if [[ "$ssh_auth_ban_enable" == 'true' ]]; then
    agent_args+=(--ssh-auth-ban-enable --ssh-auth-ban-after "$ssh_auth_ban_after" --ssh-auth-ban-duration "$ssh_auth_ban_duration" --ssh-auth-ban-mode "$ssh_auth_ban_mode")
    if [[ "$ssh_auth_ban_dry_run" == 'true' ]]; then
      agent_args+=(--ssh-auth-ban-dry-run)
    fi
    if [[ -n "$ssh_auth_ban_whitelist" ]]; then
      agent_args+=(--ssh-auth-ban-whitelist "$ssh_auth_ban_whitelist")
    fi
  fi
fi
agent_args+=("${agent_args_extra[@]}")

printf -v exec_start '%q ' "$BINARY" "${agent_args[@]}"
exec_start="${exec_start% }"

cat > "$SERVICE" <<SERVICE
[Unit]
Description=Komari Safe Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=TZ=${timezone}
Environment=AGENT_SSH_LOGIN_NOTIFY=true
ExecStart=${exec_start}
WorkingDirectory=${INSTALL_DIR}
Restart=always
RestartSec=5
User=root
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now "$unit"
systemctl restart "$unit"
systemctl --no-pager --full status "$unit"

echo
echo 'Installed Komari Safe Agent.'
echo 'Remote shell/WebSSH is removed in this build; optional TCP probing remains constrained by the agent defaults or your explicit allow-list.'
